version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/shinyongjun-nextjs
    overwrite: yes
permissions:
  - object: /var/www/html/shinyongjun-nextjs
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall: # AfterInstall 즉, 배포 완료 후 실행할 동작 설정.
    - location: deploy.sh # deploy.sh를 실행.
      timeout: 1000 # 제한 시간 1000초 으로 설정. 1000초가 넘어가면 실패함.
      runas: root # run as root 즉, root 권한으로 실행.
