"use client";

import styled from "styled-components";
import StyledComponentsRegistry from "@/libs/registry";
import { ResetStyle } from "@/styles/reset";
import type { Metadata } from "next";
import TheContainer from "@/components/the/Container";
import TheHeader from "@/components/the/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <ResetStyle />
          <StyledRootLayout>
            <TheHeader />
            <TheContainer>{children}</TheContainer>
          </StyledRootLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

const StyledRootLayout = styled.div`
  // min-width: 1280px;
`;

export default RootLayout;
