import StyledComponentsRegistry from "@/libs/registry";
import TheContainer from "@/components/the/Container";
import TheHeader from "@/components/the/Header";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <Providers>
            <TheHeader />
            <TheContainer>{children}</TheContainer>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
